[package]
name = "freya-skia-svg-macros"

description = "Skia SVG Macros for Dom bindings"
version = "0.103.0"
edition.workspace = true
rust-version.workspace = true

homepage = "https://github.com/marc2332/rust-skia"
repository = "https://github.com/marc2332/rust-skia"
documentation = "https://rust-skia.github.io/doc/skia_safe"
license = "MIT"

[lib]
name = "skia_svg_macros"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.87"
quote = "1.0.37"
syn = { version = "3.0.3", features = ["full"] }
